version: '3.8'
services:
  frontend-test-gradiweb:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    container_name: frontend-test-gradiweb
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
