export const route = "articles";

export const LIST_SET_PARAMS = "LIST_SET_PARAMS";
export const LIST_FETCH_REQUEST = "LIST_FETCH_REQUEST";
export const LIST_FETCH_SUCCESS = "LIST_FETCH_SUCCESS";
export const LIST_FETCH_FAILURE = "LIST_FETCH_FAILURE";

export const SET_DATA = "SET_DATA";

export const SCRAPP_FETCH_REQUEST = "SCRAPP_FETCH_REQUEST";
export const SCRAPP_FETCH_SUCCESS = "SCRAPP_FETCH_SUCCESS";
export const SCRAPP_FETCH_FAILURE = "SCRAPP_FETCH_FAILURE";

export const CATEGORIES_FETCH_REQUEST = "CATEGORIES_FETCH_REQUEST";
export const CATEGORIES_FETCH_SUCCESS = "CATEGORIES_FETCH_SUCCESS";
export const CATEGORIES_FETCH_FAILURE = "CATEGORIES_FETCH_FAILURE";

export const AUTHORS_FETCH_REQUEST = "AUTHORS_FETCH_REQUEST";
export const AUTHORS_FETCH_SUCCESS = "AUTHORS_FETCH_SUCCESS";
export const AUTHORS_FETCH_FAILURE = "AUTHORS_FETCH_FAILURE";
